theme: jekyll-theme-minimal
title: Dr James A. G. Jackman
author:
  name: James A. G. Jackman
  email: jamesjackman@asu.edu
minima:
  # generate social links in footer
  social_links:
    twitter: jackmanjames26
    
header_pages:
 - about.md
